Create Cover section of Hien's Portfolito project.
hienphan0111/Hien-Portfolio pull request #2
Opened 2022-12-01 04:03 UTC by hienphan0111

- Create new repo

- Setup linter

- Create 2 section of project:

   1. the toolbar (or header)

   2. the headline section (right after the header)

2022-12-01 05:22 UTC, binhussen requested changes
Hi @hienphan0111 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media0.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights

- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️

## Required Changes ♻️
-  Kindly, keep semantic tags for readability and search engines.
## Optional suggestions
- [Optional] please make your code clean,
- [Optional] kindly, keep all Figma design font, color and px by px
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-01 05:22 UTC, binhussen commented on styles.css
> +  position: realative;
- [Optional] Please, type the properties and values correctly, and remove unusable codes. 🥇

2022-12-01 05:22 UTC, binhussen commented on index.html
> +        <img src="/image/logoipsum-265.svg" alt="Logo" class="logo">
- [Optional] kindly, use `<a>` for logo, you can use the `<img>` inside `<a>` for three reasons: convention, semantics, and user experience(UX). [Check this link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more info.

2022-12-01 05:22 UTC, binhussen commented on index.html
> +                </div>
- Kindle, make contact lists inside `<ul>` instead of `<div>`  and make each `<img>` inside `<li>` as your previous code reviewer suggested you,

2022-12-01 07:03 UTC, emmiiorji approved these changes
Hi @hienphan0111 , 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Congrats](https://user-images.githubusercontent.com/20554583/204921935-8884c611-a2b5-4af5-81d5-aff598294d41.gif)

## Good Highlights

- Linter checks are passing
- Good commit messages
- Requested changes have been implemented

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-01 07:03 UTC, emmiiorji commented on index.html
> +                </ul>
[Optional] Kindly make the social icons as close to the design as possible using the exact symbols.  @Also, as you may notice, there's no icon for WhatsApp on the figma design but there are Twitter, LinkedIn, Medium, GitHub and Angelist (Now called Wellfound) icons.

Your design:
![image](https://user-images.githubusercontent.com/20554583/204986804-75096301-860e-49cb-9d36-b90a5991e613.png)



Figma design:
![image](https://user-images.githubusercontent.com/20554583/204986649-6ca9d712-d0c2-49e9-9163-4f1acfd94f93.png)

2022-12-01 07:03 UTC, emmiiorji commented on index.html
> +            <div class="hamberger"></div>
[Optional] In order to match the design as closely as possible, kindly modify the hamburger icon to have equal widths and same color as the design.

Your design:
![image](https://user-images.githubusercontent.com/20554583/204986979-a306e098-9ff9-48fd-9869-85d0f4702533.png)


Figma design:
![image](https://user-images.githubusercontent.com/20554583/204987038-43c02433-0d10-40d6-8760-2aec26ccf834.png)

2022-12-01 07:11 UTC, merged

2022-12-13 07:22 UTC, cindykandie commented on index.html
> +                    <li><img src="./image/twister.png" alt="twister" class="contact-icon"></li>
Kindly ensure you make the social media icons links to your social media accounts so it leads the visitor to your specific profile.