Build the Contact section
hienphan0111/Hien-Portfolio pull request #4
Opened 2022-12-06 15:11 UTC by hienphan0111

- Make the contact form in the footer.

2022-12-06 16:04 UTC, Tufahel requested changes
Hi @hienphan0111 @Uchenna-ibute :wave:  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code. 

## Invalid Code Review Request

You have submitted a project, but you did not add linter files (`.stylelintrc.json`, `.hintrc`) for the linters check rather, you ignored the `.stylelintrc.json` file in `.gitignore`. Kindly add those files and consider not putting them inside `.gitignore` as we can't be sure you have edited those `.linter` files or not if those are on `.gitignore`.

![32](https://user-images.githubusercontent.com/60083437/205959241-8038f25d-43c0-4d86-9b7c-dc66d4f33608.jpg)

- Kindly add linters following [Microverse linters guidelines ](https://github.com/microverseinc/linters-config/tree/master/html-css)and apply for another review.


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-06 16:27 UTC, levy002 requested changes
## Hello @hienphan0111   , :wave:
### I'm Levy, your PR reviewer

Excellent work :sunglasses: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-06 16:27 UTC, levy002 commented on styles.css
>  }
- [ ] Kindly make sure your background is visible in order to look like the provided Figma design. :wink: 

   - ### YOUR DESIGN
    ![image](https://user-images.githubusercontent.com/87197412/205966693-8a1d840e-f118-462c-9807-21343d4af078.png)


   - ### FIGMA DESIGN 
   
     ![image](https://user-images.githubusercontent.com/87197412/205967257-cfc13aa1-a457-4a05-a5a9-2bbb2ad0cbf0.png)

2022-12-07 03:27 UTC, Tadesse-Alemayehu approved these changes
### Hi @hienphan0111 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![68747470733a2f2f692e67696665722e636f6d2f6f726967696e2f36352f36353164353034326534396532656561363365613934633039653131393731365f773230302e676966](https://user-images.githubusercontent.com/69077061/206080920-80cac5e3-aa93-4eb1-91b9-9a2f3f270a6f.gif)


## Highlights
 - [ ] Good job making the changes requested by the previous code reviewer. 🙏
 - [ ]  Correct GitHub Flow 👍🏾
 - [ ]  Good commit history 🥇
 - [ ]  Good PR title/description 💯
 - [ ]  All linters passed 🥇
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-07 03:37 UTC, merged